2023-06-15 16:11:31,223 INFO    StreamThr :41 [internal.py:wandb_internal():86] W&B internal server running at pid: 41, started at: 2023-06-15 16:11:31.222600
2023-06-15 16:11:31,224 DEBUG   HandlerThread:41 [handler.py:handle_request():144] handle_request: status
2023-06-15 16:11:31,226 INFO    WriterThread:41 [datastore.py:open_for_write():85] open: /mnt/d/PROJECTION/TianChi/STS-2D/wandb/run-20230615_161131-bqu0g1nx/run-bqu0g1nx.wandb
2023-06-15 16:11:31,235 DEBUG   SenderThread:41 [sender.py:send():369] send: header
2023-06-15 16:11:31,235 DEBUG   SenderThread:41 [sender.py:send():369] send: run
2023-06-15 16:11:32,007 DEBUG   HandlerThread:41 [handler.py:handle_request():144] handle_request: check_version
2023-06-15 16:11:32,010 INFO    SenderThread:41 [dir_watcher.py:__init__():211] watching files in: /mnt/d/PROJECTION/TianChi/STS-2D/wandb/run-20230615_161131-bqu0g1nx/files
2023-06-15 16:11:32,010 INFO    SenderThread:41 [sender.py:_start_run_threads():1100] run started: bqu0g1nx with start time 1686816691.222626
2023-06-15 16:11:32,010 DEBUG   SenderThread:41 [sender.py:send_request():396] send_request: summary_record
2023-06-15 16:11:32,013 INFO    SenderThread:41 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-06-15 16:11:32,014 DEBUG   SenderThread:41 [sender.py:send_request():396] send_request: check_version
2023-06-15 16:11:33,038 INFO    Thread-12 :41 [dir_watcher.py:_on_file_created():272] file/dir created: /mnt/d/PROJECTION/TianChi/STS-2D/wandb/run-20230615_161131-bqu0g1nx/files/wandb-summary.json
2023-06-15 16:11:33,212 DEBUG   HandlerThread:41 [handler.py:handle_request():144] handle_request: run_start
2023-06-15 16:11:33,247 DEBUG   HandlerThread:41 [system_info.py:__init__():31] System info init
2023-06-15 16:11:33,247 DEBUG   HandlerThread:41 [system_info.py:__init__():46] System info init done
2023-06-15 16:11:33,247 INFO    HandlerThread:41 [system_monitor.py:start():181] Starting system monitor
2023-06-15 16:11:33,247 INFO    SystemMonitor:41 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-06-15 16:11:33,247 INFO    HandlerThread:41 [system_monitor.py:probe():201] Collecting system info
2023-06-15 16:11:33,248 INFO    SystemMonitor:41 [interfaces.py:start():190] Started cpu monitoring
2023-06-15 16:11:33,249 INFO    SystemMonitor:41 [interfaces.py:start():190] Started disk monitoring
2023-06-15 16:11:33,251 INFO    SystemMonitor:41 [interfaces.py:start():190] Started gpu monitoring
2023-06-15 16:11:33,251 INFO    SystemMonitor:41 [interfaces.py:start():190] Started memory monitoring
2023-06-15 16:11:33,252 INFO    SystemMonitor:41 [interfaces.py:start():190] Started network monitoring
2023-06-15 16:11:33,265 DEBUG   HandlerThread:41 [system_info.py:probe():195] Probing system
2023-06-15 16:11:33,294 DEBUG   HandlerThread:41 [gitlib.py:_init_repo():53] git repository is invalid
2023-06-15 16:11:33,294 DEBUG   HandlerThread:41 [system_info.py:probe():240] Probing system done
2023-06-15 16:11:33,294 DEBUG   HandlerThread:41 [system_monitor.py:probe():210] {'os': 'Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.35', 'python': '3.9.16', 'heartbeatAt': '2023-06-15T08:11:33.265391', 'startedAt': '2023-06-15T08:11:31.191323', 'docker': None, 'cuda': None, 'args': ('wandb', 'login'), 'state': 'running', 'program': '/mnt/d/PROJECTION/TianChi/STS-2D/train.py', 'codePath': 'train.py', 'host': 'DESKTOP-LT0ASMB', 'username': 'zy', 'executable': '/home/zy/anaconda3/envs/kaggle_torch/bin/python3', 'cpu_count': 3, 'cpu_count_logical': 5, 'cpu_freq': {'current': 3192.012, 'min': 0.0, 'max': 0.0}, 'cpu_freq_per_core': [{'current': 3192.012, 'min': 0.0, 'max': 0.0}, {'current': 3192.012, 'min': 0.0, 'max': 0.0}, {'current': 3192.012, 'min': 0.0, 'max': 0.0}, {'current': 3192.012, 'min': 0.0, 'max': 0.0}, {'current': 3192.012, 'min': 0.0, 'max': 0.0}], 'disk': {'total': 250.98248672485352, 'used': 49.27421951293945}, 'gpu': 'NVIDIA GeForce RTX 4090', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 4090', 'memory_total': 25757220864}], 'memory': {'total': 24.93661880493164}}
2023-06-15 16:11:33,294 INFO    HandlerThread:41 [system_monitor.py:probe():211] Finished collecting system info
2023-06-15 16:11:33,295 INFO    HandlerThread:41 [system_monitor.py:probe():214] Publishing system info
2023-06-15 16:11:33,295 DEBUG   HandlerThread:41 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-06-15 16:11:33,297 DEBUG   HandlerThread:41 [system_info.py:_save_pip():67] Saving pip packages done
2023-06-15 16:11:33,297 DEBUG   HandlerThread:41 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-06-15 16:11:33,351 ERROR   HandlerThread:41 [system_info.py:_save_conda():85] Error saving conda packages: [Errno 2] No such file or directory: 'conda'
Traceback (most recent call last):
  File "/home/zy/anaconda3/envs/kaggle_torch/lib/python3.9/site-packages/wandb/sdk/internal/system/system_info.py", line 81, in _save_conda
    subprocess.call(
  File "/home/zy/anaconda3/envs/kaggle_torch/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/zy/anaconda3/envs/kaggle_torch/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/zy/anaconda3/envs/kaggle_torch/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'conda'
2023-06-15 16:11:33,354 DEBUG   HandlerThread:41 [system_info.py:_save_conda():86] Saving conda packages done
2023-06-15 16:11:33,356 INFO    HandlerThread:41 [system_monitor.py:probe():216] Finished publishing system info
2023-06-15 16:11:33,365 DEBUG   SenderThread:41 [sender.py:send():369] send: files
2023-06-15 16:11:33,365 INFO    SenderThread:41 [sender.py:_save_file():1354] saving file wandb-metadata.json with policy now
2023-06-15 16:11:33,373 DEBUG   HandlerThread:41 [handler.py:handle_request():144] handle_request: stop_status
2023-06-15 16:11:33,374 DEBUG   SenderThread:41 [sender.py:send_request():396] send_request: stop_status
2023-06-15 16:11:33,625 DEBUG   SenderThread:41 [sender.py:send():369] send: telemetry
2023-06-15 16:11:34,040 INFO    Thread-12 :41 [dir_watcher.py:_on_file_created():272] file/dir created: /mnt/d/PROJECTION/TianChi/STS-2D/wandb/run-20230615_161131-bqu0g1nx/files/wandb-metadata.json
2023-06-15 16:11:34,041 INFO    Thread-12 :41 [dir_watcher.py:_on_file_created():272] file/dir created: /mnt/d/PROJECTION/TianChi/STS-2D/wandb/run-20230615_161131-bqu0g1nx/files/requirements.txt
2023-06-15 16:11:34,043 INFO    Thread-12 :41 [dir_watcher.py:_on_file_created():272] file/dir created: /mnt/d/PROJECTION/TianChi/STS-2D/wandb/run-20230615_161131-bqu0g1nx/files/conda-environment.yaml
2023-06-15 16:11:34,044 INFO    Thread-12 :41 [dir_watcher.py:_on_file_created():272] file/dir created: /mnt/d/PROJECTION/TianChi/STS-2D/wandb/run-20230615_161131-bqu0g1nx/files/output.log
2023-06-15 16:11:34,453 INFO    wandb-upload_0:41 [upload_job.py:push():133] Uploaded file /tmp/tmpd7nb413qwandb/e4vfyx4d-wandb-metadata.json
2023-06-15 16:11:36,049 INFO    Thread-12 :41 [dir_watcher.py:_on_file_modified():289] file/dir modified: /mnt/d/PROJECTION/TianChi/STS-2D/wandb/run-20230615_161131-bqu0g1nx/files/output.log
2023-06-15 16:11:36,678 DEBUG   HandlerThread:41 [handler.py:handle_request():144] handle_request: status_report
2023-06-15 16:11:38,062 INFO    Thread-12 :41 [dir_watcher.py:_on_file_modified():289] file/dir modified: /mnt/d/PROJECTION/TianChi/STS-2D/wandb/run-20230615_161131-bqu0g1nx/files/output.log
2023-06-15 16:11:41,703 DEBUG   HandlerThread:41 [handler.py:handle_request():144] handle_request: status_report
2023-06-15 16:11:42,082 INFO    Thread-12 :41 [dir_watcher.py:_on_file_modified():289] file/dir modified: /mnt/d/PROJECTION/TianChi/STS-2D/wandb/run-20230615_161131-bqu0g1nx/files/output.log
2023-06-15 16:11:44,092 INFO    Thread-12 :41 [dir_watcher.py:_on_file_modified():289] file/dir modified: /mnt/d/PROJECTION/TianChi/STS-2D/wandb/run-20230615_161131-bqu0g1nx/files/output.log
2023-06-15 16:11:46,101 INFO    Thread-12 :41 [dir_watcher.py:_on_file_modified():289] file/dir modified: /mnt/d/PROJECTION/TianChi/STS-2D/wandb/run-20230615_161131-bqu0g1nx/files/output.log
2023-06-15 16:11:46,731 DEBUG   HandlerThread:41 [handler.py:handle_request():144] handle_request: status_report
2023-06-15 16:11:48,111 INFO    Thread-12 :41 [dir_watcher.py:_on_file_modified():289] file/dir modified: /mnt/d/PROJECTION/TianChi/STS-2D/wandb/run-20230615_161131-bqu0g1nx/files/output.log
2023-06-15 16:11:48,398 DEBUG   HandlerThread:41 [handler.py:handle_request():144] handle_request: stop_status
2023-06-15 16:11:48,399 DEBUG   SenderThread:41 [sender.py:send_request():396] send_request: stop_status
2023-06-15 16:11:50,122 INFO    Thread-12 :41 [dir_watcher.py:_on_file_modified():289] file/dir modified: /mnt/d/PROJECTION/TianChi/STS-2D/wandb/run-20230615_161131-bqu0g1nx/files/output.log
2023-06-15 16:11:52,143 INFO    Thread-12 :41 [dir_watcher.py:_on_file_modified():289] file/dir modified: /mnt/d/PROJECTION/TianChi/STS-2D/wandb/run-20230615_161131-bqu0g1nx/files/output.log
2023-06-15 16:11:52,375 DEBUG   HandlerThread:41 [handler.py:handle_request():144] handle_request: status_report
2023-06-15 16:11:53,255 INFO    cpu       :41 [interfaces.py:monitor():140] Process cpu has exited.
2023-06-15 16:11:53,258 DEBUG   SystemMonitor:41 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-06-15 16:11:53,259 DEBUG   SystemMonitor:41 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2023-06-15 16:11:53,261 DEBUG   SystemMonitor:41 [system_monitor.py:_start():170] Publishing last batch of metrics
2023-06-15 16:11:53,266 DEBUG   SenderThread:41 [sender.py:send():369] send: stats
2023-06-15 16:11:54,152 INFO    Thread-12 :41 [dir_watcher.py:_on_file_modified():289] file/dir modified: /mnt/d/PROJECTION/TianChi/STS-2D/wandb/run-20230615_161131-bqu0g1nx/files/output.log
2023-06-15 16:11:54,216 INFO    MainThread:41 [internal.py:handle_exit():76] Internal process exited
